name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16'
          - '18'
          - '20'
          - '22'
          - '24'
        redis-version:
          - '6'
          - '7'
          - '8'

    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup Redis v${{ matrix.redis-version }}
      uses: supercharge/redis-github-action@1.8.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: set up luacheck
      run: sudo apt install -y lua-check

    - run: npm install

    - run: npm run lint
    - run: npm test
